### ISSUE TITLE
Need help to use it in the apache karaf/service mix enviroments

### ISSUE THREAD

**Issue by vMuvvala459** [uber-common/jvm-profiler#29]
Hi, We are trying to integrate the jvm-profile in the service mix/apache karaf environment. when we try to use method duration profiler, we got below error.however by default cpuandMemory profiler is working.

java.lang.NoClassDefFoundError: com/uber/profiling/transformers/MethodProfilerStaticProxy

**Comment by boy-uber** [comment]
Hi, would you share your command line running with the jvm profiler, and the full error stacktrace?

**Comment by vMuvvala459** [comment]
Hi Sorry for the late response. Below are the details.

1) installed service mix in debian 
2) created simple bundle and deployed it in the apache service mix.
3) created jvm-profile jar by runining mvn clean package
4) copied jvm-profiler.jar to /home/apache-servicemix-7.0.1/lib/boot/ directory.
5) edited  <service_mix_home_directory>/etc/config.properties.

org.osgi.framework.bootdelegation

 org.apache.xml.serialize, \                             ( existing/default last entry)
    com.uber.profiling \                                   ( add this line at the end).

5) edit servicemix.sh file to include -javaagent 

javagent="/home/extreme/apache-servicemix-7.0.1/lib/boot/jvm-profiler-1.0.0.jar=reporter=com.uber.profiling.reporters.ConsoleOutputReporter,tag=mytag,metricInterval=5000,\
durationProfiling=com.learning.bundle.simplebundle.Activator.method1"


below is the stack trace.


servicemix: JAVA_HOME not set; results may vary
Java Agent 1.0.0 premain args: reporter=com.uber.profiling.reporters.ConsoleOutputReporter,tag=mytag,metricInterval=5000,durationProfiling=com.learning.bundle.simplebundle.Activator.method1
1544192645859 com.uber.profiling.Arguments: Got argument value for reporter: com.uber.profiling.reporters.ConsoleOutputReporter
1544192645859 com.uber.profiling.Arguments: Got argument value for metricInterval: 5000
1544192645859 com.uber.profiling.Arguments: Got argument value for tag: mytag
1544192645859 com.uber.profiling.Arguments: Got argument value for durationProfiling: com.learning.bundle.simplebundle.Activator.method1
ConsoleOutputReporter - ProcessInfo: {"jvmInputArguments":"","jvmClassPath":"","epochMillis":1544192646015,"cmdline":"/usr/bin/java -javaagent:/home/extreme/apache-servicemix-7.0.1/lib/boot/jvm-profiler-1.0.0.jar=reporter=com.uber.profiling.reporters.ConsoleOutputReporter,tag=mytag,metricInterval=5000,durationProfiling=com.learning.bundle.simplebundle.Activator.method1 -server -Xms128M -Xmx512M -XX:+UnlockDiagnosticVMOptions -XX:+UnsyncloadClass -Dcom.sun.management.jmxremote -Djava.endorsed.dirs=/usr/lib/jvm/java-8-oracle/jre/jre/lib/endorsed:/usr/lib/jvm/java-8-oracle/jre/lib/endorsed:/home/apache-servicemix-7.0.1/lib/endorsed -Djava.ext.dirs=/usr/lib/jvm/java-8-oracle/jre/jre/lib/ext:/usr/lib/jvm/java-8-oracle/jre/lib/ext:/home/apache-servicemix-7.0.1/lib/ext -Dkaraf.instances=/home/apache-servicemix-7.0.1/instances -Dkaraf.home=/home/apache-servicemix-7.0.1 -Dkaraf.base=/home/apache-servicemix-7.0.1 -Dkaraf.data=/home/apache-servicemix-7.0.1/data -Dkaraf.etc=/home/apache-servicemix-7.0.1/etc -Dkaraf.restart.jvm.supported=true -Djava.io.tmpdir=/home/apache-servicemix-7.0.1/data/tmp -Djava.util.logging.config.file=/home/apache-servicemix-7.0.1/etc/java.util.logging.properties -Dkaraf.startLocalConsole=true -Dkaraf.startRemoteShell=true -classpath /home/apache-servicemix-7.0.1/lib/boot/jvm-profiler-1.0.0.jar:/home/apache-servicemix-7.0.1/lib/boot/org.apache.karaf.diagnostic.boot-4.0.9.jar:/home/apache-servicemix-7.0.1/lib/boot/org.apache.karaf.jaas.boot-4.0.9.jar:/home/apache-servicemix-7.0.1/lib/boot/org.apache.karaf.main-4.0.9.jar:/home/apache-servicemix-7.0.1/lib/boot/org.osgi.core-6.0.0.jar org.apache.karaf.main.Main ","appId":null,"name":"5346@EX09-DEB8-13","host":"EX09-DEB8-13","processUuid":"4da3d9b4-1a82-4bed-87bf-c3c1e337ab59","agentVersion":"1.0.0","appClass":null,"tag":"mytag","xmxBytes":536870912,"appJar":null}
1544192646334 com.uber.profiling.AgentImpl: Finished one time profiler: com.uber.profiling.profilers.ProcessInfoProfiler@1e88b3c
ConsoleOutputReporter - CpuAndMemory: {"nonHeapMemoryTotalUsed":1.1333528E7,"bufferPools":[{"totalCapacity":8191,"name":"direct","count":1,"memoryUsed":8191},{"totalCapacity":0,"name":"mapped","count":0,"memoryUsed":0}],"heapMemoryTotalUsed":2.4718416E7,"vmRSS":58478592,"epochMillis":1544192646340,"nonHeapMemoryCommitted":1.3828096E7,"heapMemoryCommitted":1.28974848E8,"memoryPools":[{"peakUsageMax":251658240,"usageMax":251658240,"peakUsageUsed":507648,"name":"Code Cache","peakUsageCommitted":2555904,"usageUsed":507648,"type":"Non-heap memory","usageCommitted":2555904},{"peakUsageMax":-1,"usageMax":-1,"peakUsageUsed":9729016,"name":"Metaspace","peakUsageCommitted":10092544,"usageUsed":9729016,"type":"Non-heap memory","usageCommitted":10092544},{"peakUsageMax":1073741824,"usageMax":1073741824,"peakUsageUsed":1098576,"name":"Compressed Class Space","peakUsageCommitted":1179648,"usageUsed":1098576,"type":"Non-heap memory","usageCommitted":1179648},{"peakUsageMax":168296448,"usageMax":168296448,"peakUsageUsed":24718416,"name":"PS Eden Space","peakUsageCommitted":34078720,"usageUsed":24718416,"type":"Heap memory","usageCommitted":34078720},{"peakUsageMax":5242880,"usageMax":5242880,"peakUsageUsed":0,"name":"PS Survivor Space","peakUsageCommitted":5242880,"usageUsed":0,"type":"Heap memory","usageCommitted":5242880},{"peakUsageMax":358088704,"usageMax":358088704,"peakUsageUsed":0,"name":"PS Old Gen","peakUsageCommitted":89653248,"usageUsed":0,"type":"Heap memory","usageCommitted":89653248}],"processCpuLoad":5.294810597090132E-9,"systemCpuLoad":0.03212654764878385,"processCpuTime":540000000,"vmHWM":58478592,"appId":null,"name":"5346@EX09-DEB8-13","host":"EX09-DEB8-13","processUuid":"4da3d9b4-1a82-4bed-87bf-c3c1e337ab59","tag":"mytag","gc":[{"collectionTime":0,"name":"PS Scavenge","collectionCount":0},{"collectionTime":0,"name":"PS MarkSweep","collectionCount":0}]}
1544192646349 com.uber.profiling.AgentImpl: Ran periodic profiler (first run): com.uber.profiling.profilers.CpuAndMemoryProfiler@1794d431
1544192646349 com.uber.profiling.AgentImpl: Ran periodic profiler (first run): com.uber.profiling.profilers.MethodDurationProfiler@42e26948
1544192646355 com.uber.profiling.AgentImpl: Scheduled profiler com.uber.profiling.profilers.CpuAndMemoryProfiler@1794d431 with interval 5000 millis
1544192646356 com.uber.profiling.AgentImpl: Scheduled profiler com.uber.profiling.profilers.MethodDurationProfiler@42e26948 with interval 5000 millis
ConsoleOutputReporter - CpuAndMemory: {"nonHeapMemoryTotalUsed":1.1542144E7,"bufferPools":[{"totalCapacity":8192,"name":"direct","count":1,"memoryUsed":8192},{"totalCapacity":0,"name":"mapped","count":0,"memoryUsed":0}],"heapMemoryTotalUsed":2.5400016E7,"vmRSS":59019264,"epochMillis":1544192646356,"nonHeapMemoryCommitted":1.3828096E7,"heapMemoryCommitted":1.28974848E8,"memoryPools":[{"peakUsageMax":251658240,"usageMax":251658240,"peakUsageUsed":511360,"name":"Code Cache","peakUsageCommitted":2555904,"usageUsed":511360,"type":"Non-heap memory","usageCommitted":2555904},{"peakUsageMax":-1,"usageMax":-1,"peakUsageUsed":9904576,"name":"Metaspace","peakUsageCommitted":10092544,"usageUsed":9904576,"type":"Non-heap memory","usageCommitted":10092544},{"peakUsageMax":1073741824,"usageMax":1073741824,"peakUsageUsed":1126208,"name":"Compressed Class Space","peakUsageCommitted":1179648,"usageUsed":1126208,"type":"Non-heap memory","usageCommitted":1179648},{"peakUsageMax":168296448,"usageMax":168296448,"peakUsageUsed":25400016,"name":"PS Eden Space","peakUsageCommitted":34078720,"usageUsed":25400016,"type":"Heap memory","usageCommitted":34078720},{"peakUsageMax":5242880,"usageMax":5242880,"peakUsageUsed":0,"name":"PS Survivor Space","peakUsageCommitted":5242880,"usageUsed":0,"type":"Heap memory","usageCommitted":5242880},{"peakUsageMax":358088704,"usageMax":358088704,"peakUsageUsed":0,"name":"PS Old Gen","peakUsageCommitted":89653248,"usageUsed":0,"type":"Heap memory","usageCommitted":89653248}],"processCpuLoad":0.07692307692307693,"systemCpuLoad":0.14285714285714285,"processCpuTime":550000000,"vmHWM":59019264,"appId":null,"name":"5346@EX09-DEB8-13","host":"EX09-DEB8-13","processUuid":"4da3d9b4-1a82-4bed-87bf-c3c1e337ab59","tag":"mytag","gc":[{"collectionTime":0,"name":"PS Scavenge","collectionCount":0},{"collectionTime":0,"name":"PS MarkSweep","collectionCount":0}]}
Please wait while Apache ServiceMix is starting...
 99% [=======================================================================>]1544192650276 com.uber.profiling.transformers.JavaAgentFileTransformer: Transforming class: com.learning.bundle.simplebundle.Activator
1544192650359 com.uber.profiling.transformers.JavaAgentFileTransformer: Transformed class method: com.learning.bundle.simplebundle.Activator.method1(), durationProfiling: true, argumentProfiling: []
java.lang.NoClassDefFoundError: com/uber/profiling/transformers/MethodProfilerStaticProxy
        at com.learning.bundle.simplebundle.Activator.method1(Activator.java:44)
        at com.learning.bundle.simplebundle.Activator.start(Activator.java:31)
        at org.apache.felix.framework.util.SecureAction.startActivator(SecureAction.java:697)
        at org.apache.felix.framework.Felix.activateBundle(Felix.java:2238)
        at org.apache.felix.framework.Felix.startBundle(Felix.java:2144)
        at org.apache.felix.framework.Felix.setActiveStartLevel(Felix.java:1371)
        at org.apache.felix.framework.FrameworkStartLevelImpl.run(FrameworkStartLevelImpl.java:308)
        at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.ClassNotFoundException: com.uber.profiling.transformers.MethodProfilerStaticProxy not found by simplebundle [227]
        at org.apache.felix.framework.BundleWiringImpl.findClassOrResourceByDelegation(BundleWiringImpl.java:1550)
        at org.apache.felix.framework.BundleWiringImpl.access$200(BundleWiringImpl.java:79)
        at org.apache.felix.framework.BundleWiringImpl$BundleClassLoader.loadClass(BundleWiringImpl.java:1958)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
        ... 8 more
java.lang.NoClassDefFoundError: com/uber/profiling/transformers/MethodProfilerStaticProxy
        at com.learning.bundle.simplebundle.Activator.method1(Activator.java:44)
        at com.learning.bundle.simplebundle.Activator.start(Activator.java:31)
        at org.apache.felix.framework.util.SecureAction.startActivator(SecureAction.java:697)
        at org.apache.felix.framework.Felix.activateBundle(Felix.java:2238)
        at org.apache.felix.framework.Felix.startBundle(Felix.java:2144)
        at org.apache.felix.framework.Felix.setActiveStartLevel(Felix.java:1371)
        at org.apache.felix.framework.FrameworkStartLevelImpl.run(FrameworkStartLevelImpl.java:308)
        at java.lang.Thread.run(Thread.java:748)
java.lang.NoClassDefFoundError: com/uber/profiling/transformers/MethodProfilerStaticProxy
        at com.learning.bundle.simplebundle.Activator.method1(Activator.java:44)
        at com.learning.bundle.simplebundle.Activator.start(Activator.java:31)
        at org.apache.felix.framework.util.SecureAction.startActivator(SecureAction.java:697)
        at org.apache.felix.framework.Felix.activateBundle(Felix.java:2238)
        at org.apache.felix.framework.Felix.startBundle(Felix.java:2144)
        at org.apache.felix.framework.Felix.setActiveStartLevel(Felix.java:1371)
        at org.apache.felix.framework.FrameworkStartLevelImpl.run(FrameworkStartLevelImpl.java:308)
        at java.lang.Thread.run(Thread.java:748)
java.lang.NoClassDefFoundError: com/uber/profiling/transformers/MethodProfilerStaticProxy
        at com.learning.bundle.simplebundle.Activator.method1(Activator.java:44)
        at com.learning.bundle.simplebundle.Activator.start(Activator.java:31)
        at org.apache.felix.framework.util.SecureAction.startActivator(SecureAction.java:697)
        at org.apache.felix.framework.Felix.activateBundle(Felix.java:2238)
        at org.apache.felix.framework.Felix.startBundle(Felix.java:2144)
        at org.apache.felix.framework.Felix.setActiveStartLevel(Felix.java:1371)
        at org.apache.felix.framework.FrameworkStartLevelImpl.run(FrameworkStartLevelImpl.java:308)
        at java.lang.Thread.run(Thread.java:748)
java.lang.NoClassDefFoundError: com/uber/profiling/transformers/MethodProfilerStaticProxy
        at com.learning.bundle.simplebundle.Activator.method1(Activator.java:44)
        at com.learning.bundle.simplebundle.Activator.start(Activator.java:31)
        at org.apache.felix.framework.util.SecureAction.startActivator(SecureAction.java:697)
        at org.apache.felix.framework.Felix.activateBundle(Felix.java:2238)
        at org.apache.felix.framework.Felix.startBundle(Felix.java:2144)
        at org.apache.felix.framework.Felix.setActiveStartLevel(Felix.java:1371)
        at org.apache.felix.framework.FrameworkStartLevelImpl.run(FrameworkStartLevelImpl.java:308)
        at java.lang.Thread.run(Thread.java:748)
java.lang.NoClassDefFoundError: com/uber/profiling/transformers/MethodProfilerStaticProxy
        at com.learning.bundle.simplebundle.Activator.method1(Activator.java:44)
        at com.learning.bundle.simplebundle.Activator.start(Activator.java:31)
        at org.apache.felix.framework.util.SecureAction.startActivator(SecureAction.java:697)
        at org.apache.felix.framework.Felix.activateBundle(Felix.java:2238)
        at org.apache.felix.framework.Felix.startBundle(Felix.java:2144)
        at org.apache.felix.framework.Felix.setActiveStartLevel(Felix.java:1371)
        at org.apache.felix.framework.FrameworkStartLevelImpl.run(FrameworkStartLevelImpl.java:308)
        at java.lang.Thread.run(Thread.java:748)
java.lang.NoClassDefFoundError: com/uber/profiling/transformers/MethodProfilerStaticProxy
        at com.learning.bundle.simplebundle.Activator.method1(Activator.java:44)
        at com.learning.bundle.simplebundle.Activator.start(Activator.java:31)
        at org.apache.felix.framework.util.SecureAction.startActivator(SecureAction.java:697)
        at org.apache.felix.framework.Felix.activateBundle(Felix.java:2238)
        at org.apache.felix.framework.Felix.startBundle(Felix.java:2144)
        at org.apache.felix.framework.Felix.setActiveStartLevel(Felix.java:1371)
        at org.apache.felix.framework.FrameworkStartLevelImpl.run(FrameworkStartLevelImpl.java:308)
        at java.lang.Thread.run(Thread.java:748)
java.lang.NoClassDefFoundError: com/uber/profiling/transformers/MethodProfilerStaticProxy
        at com.learning.bundle.simplebundle.Activator.method1(Activator.java:44)
        at com.learning.bundle.simplebundle.Activator.start(Activator.java:31)
        at org.apache.felix.framework.util.SecureAction.startActivator(SecureAction.java:697)
        at org.apache.felix.framework.Felix.activateBundle(Felix.java:2238)
        at org.apache.felix.framework.Felix.startBundle(Felix.java:2144)
        at org.apache.felix.framework.Felix.setActiveStartLevel(Felix.java:1371)
        at org.apache.felix.framework.FrameworkStartLevelImpl.run(FrameworkStartLevelImpl.java:308)
        at java.lang.Thread.run(Thread.java:748)
java.lang.NoClassDefFoundError: com/uber/profiling/transformers/MethodProfilerStaticProxy
        at com.learning.bundle.simplebundle.Activator.method1(Activator.java:44)
        at com.learning.bundle.simplebundle.Activator.start(Activator.java:31)
        at org.apache.felix.framework.util.SecureAction.startActivator(SecureAction.java:697)
        at org.apache.felix.framework.Felix.activateBundle(Felix.java:2238)
        at org.apache.felix.framework.Felix.startBundle(Felix.java:2144)
        at org.apache.felix.framework.Felix.setActiveStartLevel(Felix.java:1371)
        at org.apache.felix.framework.FrameworkStartLevelImpl.run(FrameworkStartLevelImpl.java:308)
        at java.lang.Thread.run(Thread.java:748)
java.lang.NoClassDefFoundError: com/uber/profiling/transformers/MethodProfilerStaticProxy
        at com.learning.bundle.simplebundle.Activator.method1(Activator.java:44)
        at com.learning.bundle.simplebundle.Activator.start(Activator.java:31)
        at org.apache.felix.framework.util.SecureAction.startActivator(SecureAction.java:697)
        at org.apache.felix.framework.Felix.activateBundle(Felix.java:2238)
        at org.apache.felix.framework.Felix.startBundle(Felix.java:2144)
        at org.apache.felix.framework.Felix.setActiveStartLevel(Felix.java:1371)
        at org.apache.felix.framework.FrameworkStartLevelImpl.run(FrameworkStartLevelImpl.java:308)
        at java.lang.Thread.run(Thread.java:748)
100% [========================================================================]

Karaf started in 3s. Bundle stats: 225 active, 225 total
 ____                  _          __  __ _
/ ___|  ___ _ ____   _(_) ___ ___|  \/  (_)_  __
\___ \ / _ \ '__\ \ / / |/ __/ _ \ |\/| | \ \/ /
 ___) |  __/ |   \ V /| | (_|  __/ |  | | |>  <
|____/ \___|_|    \_/ |_|\___\___|_|  |_|_/_/\_\

  Apache ServiceMix (7.0.1)

Hit '<tab>' for a list of available commands
and '[cmd] --help' for help on a specific command.
Hit '<ctrl-d>' or 'system:shutdown' to shutdown ServiceMix.

karaf@root>ConsoleOutputReporter - CpuAndMemory: {"nonHeapMemoryTotalUsed":7.266932E7,"bufferPools":[{"totalCapacity":40960,"name":"direct","count":8,"memoryUsed":40960},{"totalCapacity":0,"name":"mapped","count":0,"memoryUsed":0}],"heapMemoryTotalUsed":1.070836E8,"vmRSS":398389248,"epochMillis":1544192651355,"nonHeapMemoryCommitted":8.1199104E7,"heapMemoryCommitted":2.79445504E8,"memoryPools":[{"peakUsageMax":251658240,"usageMax":251658240,"peakUsageUsed":17902144,"name":"Code Cache","peakUsageCommitted":18284544,"usageUsed":17077120,"type":"Non-heap memory","usageCommitted":18284544},{"peakUsageMax":-1,"usageMax":-1,"peakUsageUsed":49610440,"name":"Metaspace","peakUsageCommitted":55181312,"usageUsed":49610440,"type":"Non-heap memory","usageCommitted":55181312},{"peakUsageMax":1073741824,"usageMax":1073741824,"peakUsageUsed":5981760,"name":"Compressed Class Space","peakUsageCommitted":7733248,"usageUsed":5981760,"type":"Non-heap memory","usageCommitted":7733248},{"peakUsageMax":168296448,"usageMax":143130624,"peakUsageUsed":145227776,"name":"PS Eden Space","peakUsageCommitted":145227776,"usageUsed":47652104,"type":"Heap memory","usageCommitted":143130624},{"peakUsageMax":17825792,"usageMax":17825792,"peakUsageUsed":17799024,"name":"PS Survivor Space","peakUsageCommitted":17825792,"usageUsed":17799024,"type":"Heap memory","usageCommitted":17825792},{"peakUsageMax":358088704,"usageMax":358088704,"peakUsageUsed":41632472,"name":"PS Old Gen","peakUsageCommitted":118489088,"usageUsed":41632472,"type":"Heap memory","usageCommitted":118489088}],"processCpuLoad":0.48255959849435387,"systemCpuLoad":0.48895582329317266,"processCpuTime":19780000000,"vmHWM":402219008,"appId":null,"name":"5346@EX09-DEB8-13","host":"EX09-DEB8-13","processUuid":"4da3d9b4-1a82-4bed-87bf-c3c1e337ab59","tag":"mytag","gc":[{"collectionTime":123,"name":"PS Scavenge","collectionCount":11},{"collectionTime":115,"name":"PS MarkSweep","collectionCount":2}]}
logout

1544192654668 Running java agent shutdown
1544192654668 Running java agent shutdown
1544192654668 Running periodic profiler (last run): com.uber.profiling.profilers.CpuAndMemoryProfiler@1794d431
1544192654668 Running periodic profiler (last run): com.uber.profiling.profilers.CpuAndMemoryProfiler@1794d431
ConsoleOutputReporter - CpuAndMemory: {"nonHeapMemoryTotalUsed":7.2596568E7,"bufferPools":[{"totalCapacity":40960,"name":"direct","count":8,"memoryUsed":40960},{"totalCapacity":0,"name":"mapped","count":0,"memoryUsed":0}],"heapMemoryTotalUsed":1.43299992E8,"vmRSS":393551872,"epochMillis":1544192654668,"nonHeapMemoryCommitted":8.1985536E7,"heapMemoryCommitted":2.79445504E8,"memoryPools":[{"peakUsageMax":251658240,"usageMax":251658240,"peakUsageUsed":17902144,"name":"Code Cache","peakUsageCommitted":18284544,"usageUsed":16357632,"type":"Non-heap memory","usageCommitted":18284544},{"peakUsageMax":-1,"usageMax":-1,"peakUsageUsed":50189248,"name":"Metaspace","peakUsageCommitted":55836672,"usageUsed":50189248,"type":"Non-heap memory","usageCommitted":55836672},{"peakUsageMax":1073741824,"usageMax":1073741824,"peakUsageUsed":6049688,"name":"Compressed Class Space","peakUsageCommitted":7864320,"usageUsed":6049688,"type":"Non-heap memory","usageCommitted":7864320},{"peakUsageMax":168296448,"usageMax":143130624,"peakUsageUsed":145227776,"name":"PS Eden Space","peakUsageCommitted":145227776,"usageUsed":83868496,"type":"Heap memory","usageCommitted":143130624},{"peakUsageMax":17825792,"usageMax":17825792,"peakUsageUsed":17799024,"name":"PS Survivor Space","peakUsageCommitted":17825792,"usageUsed":17799024,"type":"Heap memory","usageCommitted":17825792},{"peakUsageMax":358088704,"usageMax":358088704,"peakUsageUsed":41632472,"name":"PS Old Gen","peakUsageCommitted":118489088,"usageUsed":41632472,"type":"Heap memory","usageCommitted":118489088}],"processCpuLoad":0.04677480196152395,"systemCpuLoad":0.05695963787250094,"processCpuTime":21020000000,"vmHWM":402219008,"appId":null,"name":"5346@EX09-DEB8-13","host":"EX09-DEB8-13","processUuid":"4da3d9b4-1a82-4bed-87bf-c3c1e337ab59","tag":"mytag","gc":[{"collectionTime":123,"name":"PS Scavenge","collectionCount":11},{"collectionTime":115,"name":"PS MarkSweep","collectionCount":2}]}



Please let me know if  i miss anything or need more information.

**Comment by vMuvvala459** [comment]
Below are argument details.

/usr/bin/java -javaagent:/home/extreme/apache-servicemix-7.0.1/lib/boot/jvm-profiler-1.0.0.jar=reporter=com.uber.profiling.reporters.ConsoleOutputReporter,tag=mytag,metricInterval=5000,durationProfiling=com.learning.bundle.simplebundle.Activator.method1 -server -Xms128M -Xmx512M -XX:+UnlockDiagnosticVMOptions -XX:+UnsyncloadClass -Dcom.sun.management.jmxremote -Djava.endorsed.dirs=/usr/lib/jvm/java-8-oracle/jre/jre/lib/endorsed:/usr/lib/jvm/java-8-oracle/jre/lib/endorsed:/home/apache-servicemix-7.0.1/lib/endorsed -Djava.ext.dirs=/usr/lib/jvm/java-8-oracle/jre/jre/lib/ext:/usr/lib/jvm/java-8-oracle/jre/lib/ext:/home/apache-servicemix-7.0.1/lib/ext -Dkaraf.instances=/home/apache-servicemix-7.0.1/instances -Dkaraf.home=/home/apache-servicemix-7.0.1 -Dkaraf.base=/home/apache-servicemix-7.0.1 -Dkaraf.data=/home/apache-servicemix-7.0.1/data -Dkaraf.etc=/home/apache-servicemix-7.0.1/etc -Dkaraf.restart.jvm.supported=true -Djava.io.tmpdir=/home/apache-servicemix-7.0.1/data/tmp -Djava.util.logging.config.file=/home/apache-servicemix-7.0.1/etc/java.util.logging.properties -Dkaraf.startLocalConsole=true -Dkaraf.startRemoteShell=true -classpath /home/apache-servicemix-7.0.1/lib/boot/jvm-profiler-1.0.0.jar:/home/apache-servicemix-7.0.1/lib/boot/org.apache.karaf.diagnostic.boot-4.0.9.jar:/home/apache-servicemix-7.0.1/lib/boot/org.apache.karaf.jaas.boot-4.0.9.jar:/home/apache-servicemix-7.0.1/lib/boot/org.apache.karaf.main-4.0.9.jar:/home/apache-servicemix-7.0.1/lib/boot/org.osgi.core-6.0.0.jar org.apache.karaf.main.Main

**Comment by boy-uber** [comment]
It seems the felix framework may load class in some different way? Maybe you could dig a little deep into this metho "org.apache.felix.framework.BundleWiringImpl.findClassOrResourceByDelegation" and see how it loads the class.

**Comment by boy-uber** [comment]
Close inactive issue
