### ISSUE TITLE
multiple packages/methods for duration profiling

### ISSUE THREAD

**Issue by Vkodthiv** [uber-common/jvm-profiler#69]
I have a need for profiling multiple packages. Tried
`durationProfiling=com.optum.voyager.core.persistence.service.repository.HL7ResourceRepository.*,com.optum.voyager.core.persistence.service.repository.ElasticServiceImpl.*`

with following results
`Caused by: java.lang.IllegalArgumentException: Arguments for the agent should be like: key1=value1,key2=value2
	at com.uber.profiling.Arguments.parseArgs(Arguments.java:94)
	at com.uber.profiling.Agent.premain(Agent.java:35)
`

What is the right way to specify multiple packages?

**Comment by Vkodthiv** [comment]
never mind. found the answer
durationProfiling=a.bc.foo,durationProfiling=ab.c.d.test
