### ISSUE TITLE
unable to load cache item

### ISSUE THREAD

**Issue by Vkodthiv** [uber-common/jvm-profiler#70]
I find the usage of this tool somewhat limiting. Can you call out the limitations of this framework in the README please. appreciate it.

for example see below stack trace. what is it about ?

`Caused by: java.lang.IllegalStateException: Unable to load cache item
	at org.springframework.cglib.core.internal.LoadingCache.createEntry(LoadingCache.java:79)
	at org.springframework.cglib.core.internal.LoadingCache.get(LoadingCache.java:34)
	at org.springframework.cglib.core.AbstractClassGenerator$ClassLoaderData.get(AbstractClassGenerator.java:134)
	at org.springframework.cglib.core.AbstractClassGenerator.create(AbstractClassGenerator.java:319)
	at org.springframework.cglib.proxy.Enhancer.createHelper(Enhancer.java:569)
	at org.springframework.cglib.proxy.Enhancer.createClass(Enhancer.java:416)
	at org.springframework.aop.framework.ObjenesisCglibAopProxy.createProxyClassAndInstance(ObjenesisCglibAopProxy.java:58)
	at org.springframework.aop.framework.CglibAopProxy.getProxy(CglibAopProxy.java:205)
	... 42 common frames omitted
Caused by: java.lang.VerifyError: (class: com/optum/voyager/core/persistence/service/repository/HL7ResourceRepository$$EnhancerBySpringCGLIB$$18453215, method: findHL7Resource signature: (Ljava/lang/String;Ljava/util/UUID;Lcom/optum/voyager/datamodel/enums/HL7ResourceType;)Lcom/optum/voyager/core/persistence/service/entity/HL7Resource;) Inconsistent stack height 2 != 1
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:348)`

**Comment by boy-uber** [comment]
Yeah, this is interesting. We haven't got time to look into this. If you get any findings, welcome to submit any PR.

**Comment by 15212452546** [comment]
Has the problem been solved？
